ambassador:
   #build: ../amba/.
   image: svendowideit/ambassador
   environment:
    - REDIS_PORT_6379_TCP=tcp://152.1.13.66:6379
   expose:
    - "6379"
app:
   build: ../App/.
   image: mpancha/app:ambassador
   links:
    - ambassador:redis
   ports:
    - 3000:3000
