#!/bin/sh
ROOT=`pwd`
GIT_WORK_TREE=$ROOT/../blue-www/ git checkout -f
cd $ROOT/../blue-www/
#npm install
sudo docker build -t ncsu-app .
sudo docker tag ncsu-app localhost:5000/ncsu:latest
sudo docker push localhost:5000/ncsu:latest
sudo docker pull localhost:5000/ncsu:latest
sudo docker stop app_blue
sudo docker rm app_blue
sudo docker rmi localhost:5000/ncsu:current
sudo docker tag localhost:5000/ncsu:latest localhost:5000/ncsu:current
sudo docker run -p 9090:8080 -d --name app_blue ncsu-app 
