#!/bin/bash

# Build docker image for Legacy App
docker build -t mpancha/file .

# Run Legacy App container
docker run -d -p 9001:9001 --name legacyapp mpancha/file

# Extract file generated by Legacy App using curl
curl `echo $LEGACYAPP_PORT| cut -d : -f 2-3 | cut -d / -f 3`
